# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
#Uncomment this line if you're using Swift
 use_frameworks!

target 'ProjectSettingsSwift' do
pod 'Fabric'
pod 'Crashlytics'
end

target 'ProjectSettingsSwiftTests' do

end

target 'ProjectSettingsSwiftUITests' do

end

target 'PSSwift_Dev' do
pod 'Fabric'
pod 'Crashlytics'
end

